# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/form_carro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.placa = QtWidgets.QLabel(Dialog)
        self.placa.setObjectName("placa")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.placa)
        self.input_placa = QtWidgets.QLineEdit(Dialog)
        self.input_placa.setObjectName("input_placa")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_placa)
        self.marca = QtWidgets.QLabel(Dialog)
        self.marca.setObjectName("marca")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.marca)
        self.input_marca = QtWidgets.QLineEdit(Dialog)
        self.input_marca.setObjectName("input_marca")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_marca)
        self.modelo = QtWidgets.QLabel(Dialog)
        self.modelo.setObjectName("modelo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.modelo)
        self.input_modelo = QtWidgets.QLineEdit(Dialog)
        self.input_modelo.setObjectName("input_modelo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_modelo)
        self.ano = QtWidgets.QLabel(Dialog)
        self.ano.setObjectName("ano")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ano)
        self.cor = QtWidgets.QLabel(Dialog)
        self.cor.setObjectName("cor")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.cor)
        self.input_cor = QtWidgets.QLineEdit(Dialog)
        self.input_cor.setObjectName("input_cor")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.input_cor)
        self.input_ano = QtWidgets.QLineEdit(Dialog)
        self.input_ano.setObjectName("input_ano")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_ano)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancelar = QtWidgets.QPushButton(Dialog)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout.addWidget(self.btn_cancelar)
        self.btn_salvar = QtWidgets.QPushButton(Dialog)
        self.btn_salvar.setObjectName("btn_salvar")
        self.horizontalLayout.addWidget(self.btn_salvar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.placa.setText(_translate("Dialog", "Placa"))
        self.input_placa.setPlaceholderText(_translate("Dialog", "Digite a placa"))
        self.marca.setText(_translate("Dialog", "Marca"))
        self.input_marca.setPlaceholderText(_translate("Dialog", "Digite a marca"))
        self.modelo.setText(_translate("Dialog", "Modelo"))
        self.input_modelo.setPlaceholderText(_translate("Dialog", "Digite o modelo"))
        self.ano.setText(_translate("Dialog", "Ano"))
        self.cor.setText(_translate("Dialog", "Cor"))
        self.input_cor.setPlaceholderText(_translate("Dialog", "Digite a cor"))
        self.input_ano.setPlaceholderText(_translate("Dialog", "Digite o ano"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.btn_salvar.setText(_translate("Dialog", "Salvar"))
