# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/form_os.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.cliente = QtWidgets.QLabel(Dialog)
        self.cliente.setObjectName("cliente")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cliente)
        self.combo_cliente = QtWidgets.QComboBox(Dialog)
        self.combo_cliente.setObjectName("combo_cliente")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_cliente)
        self.carro = QtWidgets.QLabel(Dialog)
        self.carro.setObjectName("carro")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.carro)
        self.combo_carro = QtWidgets.QComboBox(Dialog)
        self.combo_carro.setObjectName("combo_carro")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_carro)
        self.status = QtWidgets.QLabel(Dialog)
        self.status.setObjectName("status")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.status)
        self.combo_status = QtWidgets.QComboBox(Dialog)
        self.combo_status.setObjectName("combo_status")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.combo_status)
        self.observacoes = QtWidgets.QLabel(Dialog)
        self.observacoes.setObjectName("observacoes")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.observacoes)
        self.input_observacoes = QtWidgets.QLineEdit(Dialog)
        self.input_observacoes.setObjectName("input_observacoes")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_observacoes)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancelar = QtWidgets.QPushButton(Dialog)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout.addWidget(self.btn_cancelar)
        self.btn_salvar = QtWidgets.QPushButton(Dialog)
        self.btn_salvar.setObjectName("btn_salvar")
        self.horizontalLayout.addWidget(self.btn_salvar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cliente.setText(_translate("Dialog", "Cliente"))
        self.carro.setText(_translate("Dialog", "Carro"))
        self.status.setText(_translate("Dialog", "Status"))
        self.observacoes.setText(_translate("Dialog", "Observações"))
        self.input_observacoes.setPlaceholderText(_translate("Dialog", "Descreva"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.btn_salvar.setText(_translate("Dialog", "Salvar"))
