# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/form_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.cpf = QtWidgets.QLabel(Dialog)
        self.cpf.setObjectName("cpf")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cpf)
        self.telefone = QtWidgets.QLabel(Dialog)
        self.telefone.setObjectName("telefone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.telefone)
        self.email = QtWidgets.QLabel(Dialog)
        self.email.setObjectName("email")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.email)
        self.endereco = QtWidgets.QLabel(Dialog)
        self.endereco.setObjectName("endereco")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.endereco)
        self.nome = QtWidgets.QLabel(Dialog)
        self.nome.setObjectName("nome")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nome)
        self.input_nome = QtWidgets.QLineEdit(Dialog)
        self.input_nome.setObjectName("input_nome")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_nome)
        self.input_cpf = QtWidgets.QLineEdit(Dialog)
        self.input_cpf.setObjectName("input_cpf")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_cpf)
        self.input_telefone = QtWidgets.QLineEdit(Dialog)
        self.input_telefone.setObjectName("input_telefone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.input_telefone)
        self.input_email = QtWidgets.QLineEdit(Dialog)
        self.input_email.setObjectName("input_email")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.input_email)
        self.input_endereco = QtWidgets.QLineEdit(Dialog)
        self.input_endereco.setObjectName("input_endereco")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.input_endereco)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancelar = QtWidgets.QPushButton(Dialog)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout.addWidget(self.btn_cancelar)
        self.btn_salvar = QtWidgets.QPushButton(Dialog)
        self.btn_salvar.setObjectName("btn_salvar")
        self.horizontalLayout.addWidget(self.btn_salvar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cpf.setText(_translate("Dialog", "CPF"))
        self.telefone.setText(_translate("Dialog", "Telefone"))
        self.email.setText(_translate("Dialog", "Email"))
        self.endereco.setText(_translate("Dialog", "Endereço"))
        self.nome.setText(_translate("Dialog", "Nome"))
        self.input_nome.setPlaceholderText(_translate("Dialog", "Digite o nome"))
        self.input_cpf.setPlaceholderText(_translate("Dialog", "Digite o CPF"))
        self.input_telefone.setPlaceholderText(_translate("Dialog", "Digite o telefone"))
        self.input_email.setPlaceholderText(_translate("Dialog", "Digite o seu email"))
        self.input_endereco.setPlaceholderText(_translate("Dialog", "Digite o endereco"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.btn_salvar.setText(_translate("Dialog", "Salvar"))
