# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/form_servico.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nome = QtWidgets.QLabel(Dialog)
        self.nome.setObjectName("nome")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nome)
        self.input_nome = QtWidgets.QLineEdit(Dialog)
        self.input_nome.setObjectName("input_nome")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_nome)
        self.descricao = QtWidgets.QLabel(Dialog)
        self.descricao.setObjectName("descricao")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.descricao)
        self.input_descricao = QtWidgets.QLineEdit(Dialog)
        self.input_descricao.setObjectName("input_descricao")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_descricao)
        self.preco = QtWidgets.QLabel(Dialog)
        self.preco.setObjectName("preco")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.preco)
        self.input_preco = QtWidgets.QLineEdit(Dialog)
        self.input_preco.setObjectName("input_preco")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_preco)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancelar = QtWidgets.QPushButton(Dialog)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout.addWidget(self.btn_cancelar)
        self.btn_salvar = QtWidgets.QPushButton(Dialog)
        self.btn_salvar.setObjectName("btn_salvar")
        self.horizontalLayout.addWidget(self.btn_salvar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nome.setText(_translate("Dialog", "Nome"))
        self.descricao.setText(_translate("Dialog", "Descrição"))
        self.preco.setText(_translate("Dialog", "Preço"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.btn_salvar.setText(_translate("Dialog", "Salvar"))
