# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ordens.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_busca = QtWidgets.QLineEdit(Form)
        self.input_busca.setObjectName("input_busca")
        self.horizontalLayout.addWidget(self.input_busca)
        self.btn_buscar = QtWidgets.QPushButton(Form)
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout.addWidget(self.btn_buscar)
        self.btn_novo = QtWidgets.QPushButton(Form)
        self.btn_novo.setObjectName("btn_novo")
        self.horizontalLayout.addWidget(self.btn_novo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabela_ordens = QtWidgets.QTableWidget(Form)
        self.tabela_ordens.setObjectName("tabela_ordens")
        self.tabela_ordens.setColumnCount(5)
        self.tabela_ordens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_ordens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_ordens.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_ordens.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_ordens.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_ordens.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tabela_ordens)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_excluir = QtWidgets.QPushButton(Form)
        self.btn_excluir.setObjectName("btn_excluir")
        self.horizontalLayout_2.addWidget(self.btn_excluir)
        self.btn_editar = QtWidgets.QPushButton(Form)
        self.btn_editar.setObjectName("btn_editar")
        self.horizontalLayout_2.addWidget(self.btn_editar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.input_busca.setPlaceholderText(_translate("Form", "Busque uma OS"))
        self.btn_buscar.setText(_translate("Form", "Buscar"))
        self.btn_novo.setText(_translate("Form", "Nova OS"))
        item = self.tabela_ordens.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.tabela_ordens.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Cliente"))
        item = self.tabela_ordens.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Status"))
        item = self.tabela_ordens.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Carro"))
        item = self.tabela_ordens.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Valor Total"))
        self.btn_excluir.setText(_translate("Form", "Excluir"))
        self.btn_editar.setText(_translate("Form", "Editar"))
